//
//  DeveloperPreview.swift
//  AirbnbAppCloneSwiftUI
//
//  Created by Mine Rala on 24.03.2024.
//

import Foundation

final class DeveloperPreview {
    static let shared = DeveloperPreview()
    var listings: [ListingModel] = [
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "person.fill",
              numberOfBedrooms: 4,
              numberOfBathrooms:3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936, 
              imageUrls: ["listing-4", "listing-2"],
              address: "124 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
              type: .villa
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Steve Johnson",
              ownerImageUrl: "person.fill",
              numberOfBedrooms: 4,
              numberOfBathrooms:3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 763,
              latitude: 32.779167,
              longitude: -96.808891,
              imageUrls: ["listing-2", "listing-4"],
              address: "AMLI 7th Street Station",
              city: "Dallas",
              state: "Texas",
              title: "Beatiful Dallas apartment in Texas",
              rating: 4.32,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              type: .apartment
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Harry Styled",
              ownerImageUrl: "person.fill",
              numberOfBedrooms: 4,
              numberOfBathrooms:3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 854,
              latitude: 29.749907,
              longitude: -95.358421,
              imageUrls: ["listing-3", "listing-1"],
              address: "105 Oak Street",
              city: "Houston",
              state: "Texas",
              title: "Beatiful Houston home in Texas",
              rating: 4.97,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .pool],
              type: .apartment
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Tiamothy Chalamet",
              ownerImageUrl: "person.fill",
              numberOfBedrooms: 4,
              numberOfBathrooms:3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 1267,
              latitude: 28.538336,
              longitude: -81.379234,
              imageUrls: ["listing-1", "listing-3"],
              address: "223 E. Concord St",
              city: "Orlando",
              state: "Florida",
              title: "Beatiful Orlando town home in Florida",
              rating: 4.74,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .kitchen, .office],
              type: .townHouse
             ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Mark Clark",
              ownerImageUrl: "person.fill",
              numberOfBedrooms: 4,
              numberOfBathrooms:3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 1034,
              latitude: 34.052235,
              longitude: -118.243683,
              imageUrls: ["listing-3", "listing-2"],
              address: "8420 FIRESTONE BLVD. DOWNEY",
              city: "Los Angeles",
              state: "California",
              title: "Beatiful Los Angles house in California",
              rating: 3.31,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .kitchen, .tv],
              type: .house
             )
    ]
}
